/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

// A aplicação (App.java) será usada para instanciar objetos das classes e testar suas
//funcionalidades. Crie um metodo estático para executar o teste de cada classe e invoque-
//os na main.

public class App {

    public static void main(String[] args) {

        // Objetos lampada - ver estados
        Lampada abajur = new Lampada(true);
        Lampada lamp2 = new Lampada(false);

        System.out.println("O abajur " + "está " + abajur.verEstado() + " e a lampada 2 " + lamp2 + " está " + lamp2.verEstado());

        // classe Pessoa
        // Pessoa alice



    }
}
